=== cubeca/api-specs/schemas/files/detail_response.json
{
    "$id": "https://docs.cubecommons.ca/schemas/files/detail_response.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "FilesDetailsResponse",
    "description": "FilesDetailsResponse",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "createdAt": {
            "type": "string"
        },
        "updatedAt": {
            "type": "string"
        },
        "storageType": {
            "type": "string"
        },
        "playerInfo": {
            "oneOf": [
                {
                    "type": "object",
                    "properties": {
                        "hlsUrl": {
                            "type": "string"
                        },
                        "dashUrl": {
                            "type": "string"
                        },
                        "videoIdOrSignedUrl": {
                            "type": "string"
                        }
                    },
                    "required": []
                },
                {
                    "type": "object",
                    "properties": {
                        "mimeType": {
                            "type": "string"
                        },
                        "fileType": {
                            "type": "string"
                        },
                        "publicUrl": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "mimeType",
                        "fileType",
                        "publicUrl"
                    ]
                }
            ]
        }
    },
    "required": [
        "id",
        "createdAt",
        "updatedAt",
        "storageType",
        "playerInfo"
    ]
}

=== cubeca/api-specs/schemas/files/detail_response.example.json
{
    "id": "c866d7b4-ed1c-43a5-84f4-31a30c6112e3",
    "createdAt": "2023-03-02T14:34:00Z",
    "updatedAt": "2023-03-02T14:34:00Z",
    "storageType": "cloudflareStream",
    "playerInfo": {
        "hlsUrl": "https://customer-ayah89x7bps0l5b8.cloudflarestream.com/bd903a6626e24f2297126e25d65e6ef1/manifest/video.m3u8",
        "dashUrl": "https://customer-ayah89x7bps0l5b8.cloudflarestream.com/bd903a6626e24f2297126e25d65e6ef1/manifest/video.mpd",
        "videoIdOrSignedUrl": "bd903a6626e24f2297126e25d65e6ef1"
    }
}
